oneup_uploader:
    resource: .
    type: uploader

sidus_file_upload.file.download:
    path:     /fileupload/{type}/download/{identifier}
    defaults: { _controller: 'SidusFileUploadBundle:File:download' }
