parameters:
    sidus_file_upload.resource.manager.class: Sidus\FileUploadBundle\Manager\ResourceManager

services:
    sidus_file_upload.resource.manager:
        class: '%sidus_file_upload.resource.manager.class%'
        arguments:
            - '@doctrine'
            - '@logger'
            - '@sidus_file_upload.registry.filesystem'
            - '@router'
